type Status = "Delivered" | "Pending";
type Quarter = "all" | "q1-2026" | "q4-2025";
interface Recognition {
  id: number;
  sender: string;
  recipient: string;
  occasion: string;
  points: number;
  date: string;
  dateVal: number;
  status: Status;
  dept: string;
  quarter: Quarter;
}
export const ALL_DATA: Recognition[] = [
  {
    id: 1,
    sender: "Kristin Watson",
    recipient: "Kristin Watson",
    occasion: "Daily Recognition",
    points: 100,
    date: "12 Jan 2026",
    dateVal: 20260112,
    status: "Delivered",
    dept: "HR",
    quarter: "q1-2026",
  },
  {
    id: 2,
    sender: "Annette Black",
    recipient: "Annette Black",
    occasion: "Milestone",
    points: 200,
    date: "12 Jan 2026",
    dateVal: 20260112,
    status: "Delivered",
    dept: "Engineering",
    quarter: "q1-2026",
  },
  {
    id: 3,
    sender: "Jacob Jones",
    recipient: "Jacob Jones",
    occasion: "Promotion",
    points: 150,
    date: "12 Jan 2026",
    dateVal: 20260112,
    status: "Delivered",
    dept: "Sales",
    quarter: "q1-2026",
  },
  {
    id: 4,
    sender: "Arlene McCoy",
    recipient: "Arlene McCoy",
    occasion: "Welcome",
    points: 120,
    date: "12 Jan 2026",
    dateVal: 20260112,
    status: "Delivered",
    dept: "HR",
    quarter: "q1-2026",
  },
  {
    id: 5,
    sender: "Cody Fisher",
    recipient: "Cody Fisher",
    occasion: "Appreciation",
    points: 50,
    date: "12 Jan 2026",
    dateVal: 20260112,
    status: "Delivered",
    dept: "Design",
    quarter: "q1-2026",
  },
  {
    id: 6,
    sender: "Arlene McCoy",
    recipient: "Arlene McCoy",
    occasion: "Welcome",
    points: 120,
    date: "12 Jan 2026",
    dateVal: 20260112,
    status: "Delivered",
    dept: "Marketing",
    quarter: "q1-2026",
  },
  {
    id: 7,
    sender: "Cody Fisher",
    recipient: "Cody Fisher",
    occasion: "Appreciation",
    points: 50,
    date: "12 Jan 2026",
    dateVal: 20260112,
    status: "Delivered",
    dept: "Engineering",
    quarter: "q1-2026",
  },
  {
    id: 8,
    sender: "Arlene McCoy",
    recipient: "Arlene McCoy",
    occasion: "Welcome",
    points: 120,
    date: "12 Jan 2026",
    dateVal: 20260112,
    status: "Delivered",
    dept: "Sales",
    quarter: "q1-2026",
  },
  {
    id: 9,
    sender: "Arlene McCoy",
    recipient: "Arlene McCoy",
    occasion: "Welcome",
    points: 120,
    date: "12 Jan 2026",
    dateVal: 20260112,
    status: "Delivered",
    dept: "HR",
    quarter: "q1-2026",
  },
  {
    id: 10,
    sender: "Cody Fisher",
    recipient: "Cody Fisher",
    occasion: "Appreciation",
    points: 50,
    date: "12 Jan 2026",
    dateVal: 20260112,
    status: "Delivered",
    dept: "Design",
    quarter: "q1-2026",
  },
  {
    id: 11,
    sender: "Marcus Reed",
    recipient: "Priya Sharma",
    occasion: "Milestone",
    points: 300,
    date: "13 Jan 2026",
    dateVal: 20260113,
    status: "Delivered",
    dept: "Engineering",
    quarter: "q1-2026",
  },
  {
    id: 12,
    sender: "Tina Nguyen",
    recipient: "Sam Park",
    occasion: "Promotion",
    points: 250,
    date: "13 Jan 2026",
    dateVal: 20260113,
    status: "Pending",
    dept: "Marketing",
    quarter: "q1-2026",
  },
  {
    id: 13,
    sender: "James Liu",
    recipient: "Elena Torres",
    occasion: "Daily Recognition",
    points: 100,
    date: "14 Jan 2026",
    dateVal: 20260114,
    status: "Delivered",
    dept: "Sales",
    quarter: "q1-2026",
  },
  {
    id: 14,
    sender: "Rachel Kim",
    recipient: "David Osei",
    occasion: "Welcome",
    points: 120,
    date: "14 Jan 2026",
    dateVal: 20260114,
    status: "Delivered",
    dept: "HR",
    quarter: "q1-2026",
  },
  {
    id: 15,
    sender: "Omar Hassan",
    recipient: "Fatima Al-Amin",
    occasion: "Appreciation",
    points: 80,
    date: "14 Jan 2026",
    dateVal: 20260114,
    status: "Delivered",
    dept: "Design",
    quarter: "q1-2026",
  },
  {
    id: 16,
    sender: "Sophie Brown",
    recipient: "Chris Evans",
    occasion: "Milestone",
    points: 200,
    date: "15 Jan 2026",
    dateVal: 20260115,
    status: "Delivered",
    dept: "Engineering",
    quarter: "q1-2026",
  },
  {
    id: 17,
    sender: "Lena Müller",
    recipient: "Yuki Tanaka",
    occasion: "Promotion",
    points: 150,
    date: "15 Jan 2026",
    dateVal: 20260115,
    status: "Delivered",
    dept: "Marketing",
    quarter: "q1-2026",
  },
  {
    id: 18,
    sender: "Carlos Perez",
    recipient: "Ana Lima",
    occasion: "Welcome",
    points: 120,
    date: "15 Jan 2026",
    dateVal: 20260115,
    status: "Delivered",
    dept: "Sales",
    quarter: "q1-2026",
  },
  {
    id: 19,
    sender: "Mei Zhang",
    recipient: "Lin Wei",
    occasion: "Daily Recognition",
    points: 100,
    date: "16 Jan 2026",
    dateVal: 20260116,
    status: "Delivered",
    dept: "HR",
    quarter: "q1-2026",
  },
  {
    id: 20,
    sender: "Arjun Patel",
    recipient: "Rohan Mehta",
    occasion: "Appreciation",
    points: 50,
    date: "16 Jan 2026",
    dateVal: 20260116,
    status: "Delivered",
    dept: "Design",
    quarter: "q1-2026",
  },
  {
    id: 21,
    sender: "Nina Okonkwo",
    recipient: "Sam Blake",
    occasion: "Milestone",
    points: 350,
    date: "20 Oct 2025",
    dateVal: 20251020,
    status: "Delivered",
    dept: "Engineering",
    quarter: "q4-2025",
  },
  {
    id: 22,
    sender: "Ben Carter",
    recipient: "Aisha Diallo",
    occasion: "Welcome",
    points: 120,
    date: "22 Oct 2025",
    dateVal: 20251022,
    status: "Delivered",
    dept: "HR",
    quarter: "q4-2025",
  },
  {
    id: 23,
    sender: "Yuna Park",
    recipient: "Felix Wagner",
    occasion: "Appreciation",
    points: 75,
    date: "01 Nov 2025",
    dateVal: 20251101,
    status: "Delivered",
    dept: "Marketing",
    quarter: "q4-2025",
  },
  {
    id: 24,
    sender: "Ivan Petrov",
    recipient: "Sana Malik",
    occasion: "Promotion",
    points: 200,
    date: "15 Nov 2025",
    dateVal: 20251115,
    status: "Pending",
    dept: "Sales",
    quarter: "q4-2025",
  },
  {
    id: 25,
    sender: "Grace Chen",
    recipient: "Luca Rossi",
    occasion: "Daily Recognition",
    points: 100,
    date: "28 Nov 2025",
    dateVal: 20251128,
    status: "Delivered",
    dept: "Design",
    quarter: "q4-2025",
  },
  {
    id: 26,
    sender: "Tom Hardy",
    recipient: "Zoe Clark",
    occasion: "Milestone",
    points: 250,
    date: "10 Dec 2025",
    dateVal: 20251210,
    status: "Delivered",
    dept: "Engineering",
    quarter: "q4-2025",
  },
  {
    id: 27,
    sender: "Amara Diop",
    recipient: "Kenji Ito",
    occasion: "Welcome",
    points: 120,
    date: "18 Dec 2025",
    dateVal: 20251218,
    status: "Delivered",
    dept: "HR",
    quarter: "q4-2025",
  },
  {
    id: 28,
    sender: "Riya Kapoor",
    recipient: "Noah Williams",
    occasion: "Appreciation",
    points: 90,
    date: "25 Dec 2025",
    dateVal: 20251225,
    status: "Delivered",
    dept: "Marketing",
    quarter: "q4-2025",
  },
  {
    id: 29,
    sender: "Leo Martinez",
    recipient: "Sarah O'Brien",
    occasion: "Promotion",
    points: 175,
    date: "30 Dec 2025",
    dateVal: 20251230,
    status: "Pending",
    dept: "Sales",
    quarter: "q4-2025",
  },
  {
    id: 30,
    sender: "Fatou Ba",
    recipient: "Raj Singh",
    occasion: "Daily Recognition",
    points: 100,
    date: "31 Dec 2025",
    dateVal: 20251231,
    status: "Delivered",
    dept: "Design",
    quarter: "q4-2025",
  },
];
